#!/usr/bin/env bash
# cursor-engram-preflight.sh — write .cursor/engram-wake.md from live session_start (WS-1)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

mkdir -p .cursor/engram-ki
export ENGRAM_KI_ARTIFACTS_DIR="${ENGRAM_KI_ARTIFACTS_DIR:-$REPO_ROOT/.cursor/engram-ki}"
export ENGRAM_PROFILE="${ENGRAM_PROFILE:-agent}"
export ENGRAM_STORE="${ENGRAM_STORE:-$HOME/.engram/stalks/}"

if [ -x "$REPO_ROOT/target/debug/engram" ]; then
  BIN="$REPO_ROOT/target/debug/engram"
elif command -v engram >/dev/null 2>&1; then
  BIN="$(command -v engram)"
else
  echo "ERROR: build engram first: cargo build -p engram-server" >&2
  exit 1
fi

echo "[cursor-preflight] wait-ready..." >&2
"$BIN" --store "$ENGRAM_STORE" wait-ready --timeout 120 || true

WAKE_FILE="$REPO_ROOT/.cursor/engram-wake.md"

python3 - "$BIN" "$ENGRAM_STORE" "$WAKE_FILE" "$REPO_ROOT" <<'PY'
import json, os, sys

repo = sys.argv[4]
sys.path.insert(0, os.path.join(repo, "tools/test-harness/python"))
from mcp_test_client import MCPTestClient

binary, store, wake_path = sys.argv[1:4]
client = MCPTestClient(
    binary,
    store,
    env_overrides={
        "ENGRAM_KI_ARTIFACTS_DIR": os.environ.get("ENGRAM_KI_ARTIFACTS_DIR", ""),
        "ENGRAM_KI_DISABLE": "1",
        "ENGRAM_DISABLE_SHEAF": "0",
    },
    default_timeout=120.0,
)
if not client.start():
    print("ERROR: MCP client failed to start", file=sys.stderr)
    sys.exit(1)

resp = client.call_tool(
    "mcp_engram_session_start",
    {"intent": "Cursor preflight wake — execute harness_injection queue"},
    timeout=120.0,
)
client.shutdown()

text = ""
if resp and "result" in resp:
    content = resp["result"].get("content") or []
    if content:
        text = content[0].get("text", "")

packet = json.loads(text) if text.startswith("{") else {}
cont = packet.get("continuation") or {}
harness = cont.get("harness_injection") or packet.get("harness_injection") or {}
actions = harness.get("suggested_actions") or []
primary = cont.get("primary_goal") or ""
ego = harness.get("ego_snapshot") or {}
playbook = harness.get("continuity_playbook") or {}

lines = ["# Engram Wake Queue\n", "> Generated by scripts/cursor-engram-preflight.sh\n\n"]
lines.append("> **MANDATORY:** Execute suggested actions before `context_for_edit` or broad reads.\n\n")
if primary:
    lines.append(f"**Primary goal:** `{primary}`\n\n")
if ego.get("present"):
    lines.append(
        f"**Ego:** step {ego.get('nrem_step','?')} · drift {ego.get('drift_velocity',0):.3f} "
        f"({ego.get('stability','?')}) · {ego.get('last_nrem_age_human','?')}\n\n"
    )
lines.append("## Suggested actions\n\n")
if not actions:
    lines.append("_Empty queue — run session_start in Cursor MCP._\n")
else:
    for i, a in enumerate(actions, 1):
        tool = a.get("tool", "?")
        reason = a.get("reason", "")
        pri = a.get("priority", 99)
        lines.append(f"{i}. **{tool}** (p={pri}) — {reason}\n")
        if a.get("args"):
            lines.append(f"   ```json\n   {json.dumps(a['args'], indent=2)}\n   ```\n")
        if a.get("draft_payload"):
            lines.append(f"   Draft tile type: `{a.get('recommended_tile_type', '?')}`\n")
if playbook.get("steps"):
    lines.append("\n## Continuity playbook\n\n")
    for s in playbook["steps"]:
        lines.append(f"{s.get('step','?')}. {s.get('action','')}\n")
lines.append("\n---\n_Lean contract: no watch_workspace at wake._\n")

os.makedirs(os.path.dirname(wake_path), exist_ok=True)
with open(wake_path, "w") as f:
    f.writelines(lines)
print(f"Wrote {wake_path} ({len(actions)} actions)")
PY

echo "[cursor-preflight] done: $WAKE_FILE" >&2